### PR TITLE
feat(exporter): skip objects with '_ignore' suffix and their children

### PR DESCRIPTION
**Pull request by NMC-TBone**
Objects with names ending in '_ignore' (+their children) are now excluded from the export process.

Example use case:
When importing an asset (e.g., a light from the game files) that you need to adjust or fit properly before exporting, you can add the light as a child under an empty (e.g., the sharedLight node in vehicle.xml). By renaming the imported light with the '_ignore' suffix, it will be excluded from the export process, ensuring it doesn’t interfere with the final output.

image
image

Can also be useful for objects like bounding volumes if you export e.g. active collection and want to keep the bv object within that collection:
image

### CODE REVIEW

**Comment by StjerneIdioten** [comment]
Couldn't this already be archived by using the child-of constraint? Or any of the other constraints for placement

**Comment by NMC-TBone** [comment]
> Couldn't this already be archived by using the child-of constraint? Or any of the other constraints for placement? It keeps the object out of the hierarchy for export, while still allowing it to be "part" of the model in Blender

Well I guess that could work as well, but thats certainly more work to setup than just adding "_ignore" to the name 😅And if you do changes to transformation/apply transformation child of constraint might need adjustments ("Set Inverse" in modifier).

Also "_ignore" suffix is part of giants exporter as well, so if people want to move from giants exporter --> community this will still work as expected 🫣

**Comment by StjerneIdioten** [comment]
> Well I guess that could work as well, but thats certainly more work to setup than just adding "_ignore" to the name 😅And if you do changes to transformation/apply transformation on parent object, child of constraint might need adjustments ("Set Inverse" in modifier).

That could be, but then I would almost rather have a property for it although I guess it is less easily visible in the UI. It just rubs me a bit to start adding extra stuff to the names that has special meanings. Most definitely not how Blender imagines that you extend their stuff 😂 

> Also "_ignore" suffix is part of giants exporter as well, so if people want to move from giants exporter --> community this will still work as expected 🫣

That might be, but I am not about to add all of the stupid crap that Giants does to this because they couldn't be bothered to try and implement something properly 😄 The conversion would be better handled by some sort of deliberate converter function, just like the Giants exporter does for e.g. the FS25 material upgrade. We aren't exactly property compatible either so there is already plenty of conversion/duplication to do if you want to switch or use both.

**Comment by NMC-TBone** [comment]
> > Well I guess that could work as well, but thats certainly more work to setup than just adding "_ignore" to the name 😅And if you do changes to transformation/apply transformation on parent object, child of constraint might need adjustments ("Set Inverse" in modifier).
> 
> That could be, but then I would almost rather have a property for it although I guess it is less easily visible in the UI. It just rubs me a bit to start adding extra stuff to the names that has special meanings. Most definitely not how Blender imagines that you extend their stuff 😂
> 
I was thinking about adding property for it, but yea nah..... Not sure, maybe?
> > Also "_ignore" suffix is part of giants exporter as well, so if people want to move from giants exporter --> community this will still work as expected 🫣
> 
> That might be, but I am not about to add all of the stupid crap that Giants does to this because they couldn't be bothered to try and implement something properly 😄 The conversion would be better handled by some sort of deliberate converter function, just like the Giants exporter does for e.g. the FS25 material upgrade. We aren't exactly property compatible either so there is already plenty of conversion/duplication to do if you want to switch or use both.

Understand what you mean 🙈

**Comment by NMC-TBone** [comment]
Thinking a bit about this, I think custom property might be the best option here?

**Comment by StjerneIdioten** [comment]
> Thinking a bit about this, I think custom property might be the best option here?

I think the only downside to a custom property would be the fact that it isn't clear from the outliner that a given object isn't exported, but I don't see that as too much of a problem. It could perhaps be written in the log that the item is ignored for export because of that property being set.

**Comment by NMC-TBone** [comment]
> I think the only downside to a custom property would be the fact that it isn't clear from the outliner that a given object isn't exported, but I don't see that as too much of a problem. It could perhaps be written in the log that the item is ignored for export because of that property being set.

Yes, sounds reasonable to me.

Do you want me to edit this PR, or should I make a new one?

**Comment by NMC-TBone** [comment]
Closing this in favor of the new PR using property instead of relying on object name. #237

**Pull request closed without merging**
