### PR TITLE
fix: tangent for skinned and merged mesh

### PR DESCRIPTION
**Pull request by LKAMinco**
Fixed tangent setting for skinned and merged meshes.

### CODE REVIEW

**Comment by StjerneIdioten** [comment]
And this is needed for skinned and merged meshes?

**Comment by LKAMinco** [comment]
As I know every mesh that contains normal should have tangent. Also I have tested it and merged mesh is not rendered without tangent flag, if it contains normal map.

**Comment by StjerneIdioten** [comment]
> As I know every mesh that contains normal should have tangent. Also I have tested it and merged mesh is not rendered without tangent flag, if it contains normal map.

Do you know if GE adds it to the I3D if you export without it and then save in GE? Because then it should definitely have it as I try and model the i3d format from whatever GE does 😂

**Comment by LKAMinco** [comment]
Nope, i3d converter haven't set that flag. What is interesting because it could be done automatically, probably something from old giants editor.

**Comment by StjerneIdioten** [comment]
> Nope, i3d converter haven't set that flag. What is interesting because it could be done automatically, probably something from old giants editor.

What exactly do you mean by "I3D converter"?

**Comment by LKAMinco** [comment]
The I3DBinarry converter that is used to convert xml to shapes. Same what does giants editor when u save it as binary. The important thing is that all meshes that have normal map needs tangent oprion.

**Comment by StjerneIdioten** [comment]
> The I3D Binary converter that is used to convert xml to shapes. Same what does giants editor when u save it as binary. The important thing is that all meshes that have normal map needs tangent option.

Ah okay. I normally just check by opening the files in GE and then saving them again (not as binary) to see if GE adds any extra flags to the file. And that is what I consider to be the "most accurate" version of how the i3d file should be.

**Pull request merged**
