### PR TITLE
feat(materials): replace surface_render_method with alpha blending property and restructure panels

### PR DESCRIPTION
**Pull request by NMC-TBone**
Replaced `surface_render_method == 'BLENDED'` check with the new `alpha_blending` property in `i3d_attributes`. Restructured material shader panels for (hopefully) improved code readability and future functionality.

Found one limitation (I think) with the new layout panels, all sub panels you make will inherrit value of the "top level" use_property_split. So had to set that to False for now. Even if you add a new use_property_split within the created panels they will still use the top-level one.

Since @LKAMinco doesn't have that much time these days he asked me to do these changes. (#211)

### CODE REVIEW

**Comment by LKAMinco** [comment]
Ohh, in fs 25, there are some shader values of type float1 what is same as float

**Comment by StjerneIdioten** [comment]
Is this compatible with FS22?

**Comment by NMC-TBone** [comment]
> Is this compatible with FS22?

should be I think

**Review by StjerneIdioten — APPROVED** [review]
I am going to approve and merge this one, but I would recommend splitting general cleanup and specific changes to features into separate pull requests going forward. Anytime the pull request message turns out as "I did this AND this AND this separate thing" then it might be too bloated

**Pull request merged**
