### PR TITLE
Add vertex color to exporter

### LINKED ISSUE #25: Vertex color?
**Describe the bug**
I switched from the original version this one was forked from to his version, and I noticed vertex colors are no longer exported. Is there an ETA for this feature? Thank you!

### PR DESCRIPTION
**Pull request by kbrandwijk**
This PR adds support for vertex color back to the exporter.

Resolves #25

### CODE REVIEW

**Comment by StjerneIdioten** [comment]
Do you know how to get vertex painting to show in Giants Engine? I have pulled your changes and changes some small things, but I would like to verify that it works before merging.

**Comment by kbrandwijk** [comment]
I'll try and whip something up. The use case I had for it was a bit too involved to share easily. I'll do a minimal example for you to use as a test case.

**Comment by StjerneIdioten** [comment]
> I'll try and whip something up. The use case I had for it was a bit too involved to share easily. I'll do a minimal example for you to use as a test case.

That sounds great

**Comment by StjerneIdioten** [comment]
I have gotten my hands on a vertexshader, so I can visualize the vertex paint data. So you don't have to create an example ;)

**Comment by StjerneIdioten** [comment]
There seems to be a problem with the vertex colour export. It is definitly not the correct value that turns up in GE from what I can deduce from both the i3d and what the shader tells me. But the thing is that the old addon creates the exact same wrong output. I have to inspect this a bit deeper to determine the cause.

**Comment by StjerneIdioten** [comment]
See #25 for explanation of changes to the code.

**Pull request merged**
