### PR TITLE
fix: fixed normals calc for Blender 4.1

### PR DESCRIPTION
**Pull request by LKAMinco**

### CODE REVIEW

**Comment by StjerneIdioten** [comment]
Have you tested that normals are still exported properly into GE with scaling? And not just that the exporter doesn't throw an error anymore. I can see that they've removed that function yes, but the they refer to using the normals from `corner_normals` to gain access to the normals cache. And the other call was there for a reason, given that the normals were messed up because of the scaling applied. But I don't know if that is still the case.

**Comment by LKAMinco** [comment]
Yes I have tested it and did not find any issue. Also they have mentioned in the api change that "it is automatically updated when relevant data changes" so I assume that Blender now recalculates normals automatically. Also `Mesh.corner_normals` is just read only collectionProp.

**Comment by StjerneIdioten** [comment]
> Also they have mentioned in the api change that "it is automatically updated when relevant data changes" so I assume that Blender now recalculates normals automatically. 

Yes, but that refers back to `mesh.corner_normals` automatically being updated as far as my english is concerned 😅 

> Also `Mesh.corner_normals` is just read only collectionProp.

I know. But maybe we are meant to access normals through this property instead, when we want updated values.

It can also just be the case that accessing the normals as we have done so far is fine and that this "fix" of updating the normals has been unnecessary for a while. This code is some of the first stuff back when 2.8 came out 😅

**Comment by LKAMinco** [comment]
I have tested it, compared and get same result in Vector for `obj.data.loops.normal` and `obj.data.corner_normals.vector`. Order was also the same. Tested on scaled, rotated, transformed mesh.

**Pull request merged**
