### PR TITLE
Update properties.py

### PR DESCRIPTION
**Pull request by SuguruGT**
Added decal layer

### CODE REVIEW

**Comment by StjerneIdioten** [comment]
Changed the branch to be develop, since this is where commits should go before eventually getting into the master for release!
And please update this pull request with the changes from https://github.com/StjerneIdioten/I3D-Blender-Addon/pull/62

Also please update the commit message to follow the format specified [here](https://github.com/StjerneIdioten/I3D-Blender-Addon#for-developers), this kind of change would go in the 'feat-small' type.

**Review by StjerneIdioten — CHANGES_REQUESTED** [review]
From what I can gather in GE 'Decal Layer' is an integer with a range of 0-4, default being 0. So the type of `decal_layer` should be a `IntProperty` with min/max set to those limits, instead of a `FloatProperty`

**Comment by SuguruGT** [comment]
Yes, it's true.
Thank you.

**Comment by StjerneIdioten** [comment]
Ehm, you made the correct changes to the files, but closed your pull request? :-P

**Comment by SuguruGT** [comment]
Sorry for closing, we thought it was necessary to close the pull request after your verification.

**Review by StjerneIdioten — CHANGES_REQUESTED** [review]
I just checked `IntProperty` on blenders api site [here](https://docs.blender.org/api/current/bpy.types.IntProperty.html#bpy.types.IntProperty.IntProperty.hard_max) and it would seems that you are supposed to use `hard_max` and `hard_min` for setting the values and also, they should be defined as integers, not floats.

**Comment by StjerneIdioten** [comment]
Also your commit messages are still not adhering to the format specified [here](https://github.com/StjerneIdioten/I3D-Blender-Addon#for-developers). It is important for the build system to properly do changelogs. I believe this kind of things belong to the `feat-small` type that I have defined.

It would be better if all the files were in one commit as well, since none of the changes are "standalone". It is one feature.
[This link](https://www.internalpointers.com/post/squash-commits-into-one-git) might help with that. I believe you get the chance to create a proper commit message as well once you squash them.

**Comment by SuguruGT** [comment]
Hope the changes are now correct.
Sorry but it's too complicated for us to contribute to your work.
I hope this project of yours continues, is developed and appreciated by all.
Thank's for your job.

**Comment by StjerneIdioten** [comment]
It's okay, I might have to redo the development information a bit to make it easier for ontributers, but I do have to assume that people contributing have at least proper knowledge of how git/github works ;-) 
If you still want to help, then feel free to add issues to the issue tracker instead, when you come across something that is missing. That way I (or someone else) can swoop in and implement it ;-)

**Pull request merged**
